project:
  type: book
  output-dir: docs

book:
  title: "ggplot2: field manual"
  author: "Martin Frigaard"
  reader-mode: true
  chapters:
    - index.qmd
    - part: univariate.qmd
      chapters: 
        - bar_graphs.qmd
        - histograms.qmd
        - frequency_polygons.qmd
        - dot_plots.qmd
        - density_plots.qmd
        - violin_plots.qmd
        - box_plots.qmd
    - part: amounts.qmd
      chapters:
        - chapter_amnts.qmd
    - part: proportions.qmd
      chapters:
        - chapter_prp.qmd
    - part: distributions.qmd
      chapters:
        - chapter_dist.qmd
    - part: relationships.qmd
      chapters:
        - chapter_rela.qmd
    - part: "References"
      chapters:
        - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    toc-title: Contents
    code-fold: show
    code-tools: false
    code-overflow: wrap
    highlight-style: arrow
    theme:
      light: flatly
      dark: darkly
    code-link: true
    callout-appearance: simple




