project:
  type: book

book:
  title: "ggplot2: field manual"
  author: "Martin Frigaard"
  reader-mode: true
  page-footer:
    left: |
      ggplot2: field manual was written by Martin Frigaard.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  page-navigation: true
  chapters:
    - index.qmd
    - part: univariate.qmd
      chapters: 
        - bar_graphs.qmd
        - histograms.qmd
        - frequency_polygons.qmd
        - dot_plots.qmd
        - density_plots.qmd
        - violin_plots.qmd
        - box_plots.qmd
    - part: amounts.qmd
      chapters:
        - grp_bar_graphs.qmd
        - sum_bar_graphs.qmd
        - overlapping_bar_graphs.qmd
        - heatmaps.qmd
        - waffle_charts.qmd
        - cleveland_dot_plots.qmd
    - part: proportions.qmd
      chapters:
        - diverging_bar_graphs.qmd
        - stacked_filled_density_graphs.qmd
        - mosaic_plots.qmd
        - pie_charts.qmd
        - treemaps.qmd
    - part: distributions.qmd
      chapters:
        - overlapping_histograms.qmd
        - overlapping_frequency_polygons.qmd
        - overlapping_dot_plots.qmd
        - beeswarm_plots.qmd
        - overlapping_stacked_density_plots.qmd
        - ridgeline_plots.qmd
        - grouped_box_plots.qmd
        - grouped_violin_plots.qmd
        - raincloud_plots.qmd
    - part: dates_and_times.qmd
      chapters:
        - line_graphs.qmd
        - grp_line_graphs.qmd
        - bump_charts.qmd
        - slope_graphs.qmd
        - stream_plots.qmd
        - alluvial_charts.qmd
        - instance_chart.qmd
    - part: relationships.qmd
      chapters:
        - scatter_plot.qmd
        - grouped_scatter_plots.qmd
        - bubble_charts.qmd
        - grouped_bubble_charts.qmd
        - parallel_sets.qmd
        - density_contours.qmd
        - bins_2d.qmd
        - hex_bins.qmd
    - part: "References"
      chapters:
        - references.qmd
  appendices:
        - xtnsns_tbl.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, custom.scss]
    highlight-style: arrow
    toc: true
    toc-depth: 5
    toc-location: right
    toc-title: Contents
    code-link: false
    code-block-bg: "#f8f8f8"
    code-block-border-left: "#99bbc9"
    code-annotations: hover
    number-sections: true
    callout-appearance: simple
    code-fold: show
    code-summary: 'show/hide'
    df-print: paged
    dpi: 320
    fig-format: retina
    fig-asp: 0.618
    fontsize: 1.085em
    linestretch: 1.25

execute:
  freeze: auto

